config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders do
    member do
      get 'confirm'
      get 'thank_you'
    end
  end

  root "orders#new"
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :products, through: :items

  accepts_nested_attributes_for :items, reject_if: ->(attrs) { attrs['quantity'].blank? || attrs['quantity'] == "0"},
    allow_destroy: true

  scope :confirmed, ->{ where(confirmed: true) }

  def confirm
    update(confirmed: true)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum type: [:admin, :salesman]

  has_many :orders, foreign_key: 'salesman_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.confirmed
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to confirm_order_path(@order)
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
    @order.update(confirmed: false)
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(order_params)
      redirect_to confirm_order_path(@order)
    else
      render 'edit'
    end
  end

  def confirm
    @order = Order.find(params[:id])
  end

  def thank_you
    @order = Order.find(params[:id])
    @order.confirm
  end

  private

  def order_params
    params.require(:order).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flash
    render "shared/flash"
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def setup_order(order)
    (Product.all - order.products).each do |product|
      order.items.build(product: product)
    end

    order
  end
end

app/views/clients/_search.html.haml
= form_tag clients_path, method: 'get', remote: true do
  .form-group
    = label_tag :search, "Número de Cliente"
    = text_field_tag :search, params[:search], class: 'form-control', placeholder: "Introduzca el código del cliente: "
  = submit_tag "Buscar Cliente", name: nil, class: 'btn btn-primary', data: { disable_with: "Buscando..."}

app/views/clients/index.html.haml
%h1 Clientes

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FerrelinkPedidos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header-wrapper">
    <div class="header">
      <a href="http://ferrelink.com/en/" id="logo">Ferrelink</a>
    </div>
  </div>
  <div class="container">
    <%= render_flash %>

    <%= yield %>

    <hr>
    <footer>
      <p class="text-muted">Ferrelink © 2010 - 2015 Todos los derechos reservados</p>
    </footer>
  </div>
  <hr>
</body>
</html>

app/views/orders/_form.html.haml
%hr
%h3.text-primary Datos del Cliente

.form-inline
  .form-group
    = f.label :client_name, "Nombre:"
    = f.text_field :client_name, class: "form-control"
  .form-group
    = f.label :client_code, "Código:"
    = f.text_field :client_code, class: "form-control"

%hr

%h3.text-primary Productos
%table.table.products_table
  %thead
    %tr
      %th Codigo
      %th Descripción
      %th Precio
      %th Unidad
      %th Bulto
      %th Venta minima
      %th Cantidad
      - unless f.object.new_record?
        %th Eliminar
  %tbody
    = f.fields_for :items do |ff|
      - product = ff.object.product
      %tr
        %td.align-left= product.code
        %td.align-left= product.description
        %td= product.price
        %td= product.unit
        %td= product.bundle
        %td.js_minimum
          = product.minimum_sale
        %td
          = ff.label :quantity, class: "control-label hide"
          = ff.number_field :quantity, class: "form-control quantity-field js_quantity", data: { container: 'body', toggle: 'popover', content: 'La cantidad debe ser múltiplo de la venta mínima'}

        - if ff.object.quantity.present?
          %td= ff.check_box :_destroy
        = ff.hidden_field :product_id, value: product.id

app/views/orders/_order.html.haml
%tr
  %td.align-left
    = link_to order.id, order
  %td.align-left= order.client_name
  %td.align-left salesman name

app/views/orders/confirm.html.haml
%h1 Confirmar Pedido
%hr
%h2.span.text-primary
  = "#{@order.client_name} - #{@order.client_code}"

%table.table
  %thead
    %tr
      %th Codigo
      %th Descripcion
      %th Precio (Bs)
      %th Unidad
      %th Bulto
      %th Venta minima
      %th Cantidad
  %tbody
    - @order.items.each do |item|
      - product = item.product
      %tr
        %td= product.code
        %td= product.description
        %td= product.price
        %td= product.unit
        %td= product.bundle
        %td= product.minimum_sale
        %td= item.quantity

= link_to "Confirmar", thank_you_order_path(@order), class: "btn btn-success"
= link_to "Regresar", edit_order_path(@order), class: "btn btn-default"

app/views/orders/edit.html.haml
%h1 Editar pedido

= form_for setup_order(@order)do |f|
  = render 'form', f: f
  = f.submit "Proceder", class: "btn btn-primary"

app/views/orders/index.html.haml
%h1 Órdenes
%hr

%table.table
  %thead
    %th Número
    %th Cliente
    %th Vendedor
  %tbody
    = render partial: 'order', collection: @orders

app/views/orders/new.html.haml
%h1 Realizar pedido

= form_for setup_order(@order)do |f|
  = render 'form', f: f
  = f.submit "Totalizar Pedido", class: "btn btn-primary", disabled: true

app/views/orders/thank_you.html.haml
%h1 Gracias por su pedido

En breve nos pondremos en contacto con usted.

app/views/shared/_flash.html.haml
- flash.each do |name, msg|
  = content_tag div, msg, class: name